const CHANGE_SELECTED_COLOR = 'CHANGE_SELECTED_COLOR';
const CHANGE_SELECTED_TEXTURE = 'CHANGE_SELECTED_TEXTURE';
const CHANGE_SELECTED_BACKGROUND = 'CHANGE_SELECTED_BACKGROUND';

export {
  CHANGE_SELECTED_COLOR,
  CHANGE_SELECTED_TEXTURE,
  CHANGE_SELECTED_BACKGROUND,
};
